/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.Component;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Element;
import javax.swing.text.TableView;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import util.Stupid;
import util.Stupid.stupid;

/**
 *
 * @author rofler
 */
public class AlbumDetails extends javax.swing.JFrame {

    private static JSONArray albums;
    private static JSONObject album;
    private static JSONArray tracks;
    private static int id;

    /**
     * Creates new form AlbumDetails
     */
    public AlbumDetails(JSONArray albums, int id) {

        this.id = id;
        this.album = (JSONObject) albums.get(id);
        this.tracks = (JSONArray) album.get("tracks");

        table_tracks = new JTable(new DefaultTableModel(new Object[]{"number", "title"}, 0));

        ImageIcon picture = new ImageIcon(stupid.getPath_to_pics() + album.get("pic_name").toString());
        Image im = picture.getImage();
        Image new_im = im.getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
        picture.setImage(new_im);
        //      image_label.setVisible(true);

        initComponents();

        image_label.setIcon(picture);
        image_label.setBounds(0, 0, 0, 0);

        text_AlbumArtist.setText(album.get("artist").toString());
        text_AlbumTitle.setText(album.get("title").toString());
        text_Genre.setText(album.get("genre").toString());
        text_comment.setText(album.get("comment").toString());
        text_id.setText(album.get("id").toString());

        text_AlbumArtist.setEditable(false);
        text_AlbumTitle.setEditable(false);
        text_Genre.setEditable(false);
        text_comment.setEditable(false);
        text_id.setEditable(false);

        //new DefaultTableModel(new Object[]{"number", "title"}));
        DefaultTableModel table_tracks_model = (DefaultTableModel) table_tracks.getModel();

        for (int i = 0; i < tracks.size(); i++) {
            JSONObject track = (JSONObject) tracks.get(i);

            table_tracks_model.addRow(new Object[]{track.get("number").toString(), track.get("title").toString()});
            table_tracks.setModel(table_tracks_model);
        }

        table_tracks.setEnabled(false);

        button_Cancel.setVisible(false);
        button_AddTrack.setVisible(false);
        button_DeleteTrack.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_AlbumTitle = new javax.swing.JTextField();
        text_AlbumArtist = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        text_Genre = new javax.swing.JTextField();
        label3 = new java.awt.Label();
        text_comment = new javax.swing.JTextField();
        label4 = new java.awt.Label();
        text_id = new javax.swing.JTextField();
        label5 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_tracks = new javax.swing.JTable();
        label6 = new java.awt.Label();
        button_change = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        checkBox_Approved = new javax.swing.JCheckBox();
        button_AddTrack = new javax.swing.JButton();
        button_DeleteTrack = new javax.swing.JButton();
        button_Cancel = new javax.swing.JButton();
        button_Back = new javax.swing.JButton();
        image_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setText("Album Title");

        label2.setText("Artist Name");

        label3.setText("Album Genre");

        label4.setText("Album Genre");

        label5.setText("Album id");

        table_tracks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Title"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_tracks);

        label6.setText("Tracks");

        button_change.setText("Edit");
        button_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_changeActionPerformed(evt);
            }
        });

        jLabel1.setText("Approved");

        button_AddTrack.setText("Add Track");
        button_AddTrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_AddTrackActionPerformed(evt);
            }
        });

        button_DeleteTrack.setText("Delete Track");
        button_DeleteTrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_DeleteTrackActionPerformed(evt);
            }
        });

        button_Cancel.setText("Cancel");
        button_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CancelActionPerformed(evt);
            }
        });

        button_Back.setText("Back");
        button_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_AlbumTitle)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(text_AlbumArtist, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(text_Genre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(image_label, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(text_id, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(394, 394, 394))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_change)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(button_DeleteTrack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(button_AddTrack, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addComponent(button_Cancel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkBox_Approved)
                                .addGap(325, 325, 325)
                                .addComponent(button_Back))
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_comment, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(500, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text_AlbumTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(text_AlbumArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(image_label, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(text_Genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(text_comment, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_change)
                            .addComponent(button_AddTrack)
                            .addComponent(button_Cancel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_DeleteTrack)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkBox_Approved))
                    .addComponent(button_Back))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Index().setVisible(true);
    }//GEN-LAST:event_button_BackActionPerformed

    private void button_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_changeActionPerformed
        // TODO add your handling code here:
        if (button_change.getText().equals("Edit")) {
            button_change.setText("Save");
            button_AddTrack.setVisible(true);
            button_Cancel.setVisible(true);
            button_DeleteTrack.setVisible(true);
            button_Back.setVisible(false);

            text_AlbumArtist.setEditable(true);
            text_AlbumTitle.setEditable(true);
            text_Genre.setEditable(true);
            text_comment.setEditable(true);
            table_tracks.setEnabled(true);

        } else if (button_change.getText().equals("Save")) {
            //to do -> save to json

            button_change.setText("Edit");
            button_AddTrack.setVisible(false);
            button_Cancel.setVisible(false);
            button_DeleteTrack.setVisible(false);
            button_Back.setVisible(true);

            text_AlbumArtist.setEditable(false);
            text_AlbumTitle.setEditable(false);
            text_Genre.setEditable(false);
            text_comment.setEditable(false);
            table_tracks.setEnabled(false);
        }
    }//GEN-LAST:event_button_changeActionPerformed

    private void button_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CancelActionPerformed
        // TODO add your handling code here:

        button_change.setText("Edit");
        button_AddTrack.setVisible(false);
        button_Cancel.setVisible(false);
        button_DeleteTrack.setVisible(false);
        button_Back.setVisible(true);
    }//GEN-LAST:event_button_CancelActionPerformed

    private void button_DeleteTrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_DeleteTrackActionPerformed
        // TODO add your handling code here:

        System.err.println(table_tracks.getValueAt(table_tracks.getSelectedRow(), 0));

    }//GEN-LAST:event_button_DeleteTrackActionPerformed

    private void button_AddTrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_AddTrackActionPerformed
        // TODO add your handling code here:
        
        new AddTrack(albums, id).setVisible(true);
        this.setEnabled(false);
        
    }//GEN-LAST:event_button_AddTrackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlbumDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlbumDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlbumDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlbumDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlbumDetails(albums, id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_AddTrack;
    private javax.swing.JButton button_Back;
    private javax.swing.JButton button_Cancel;
    private javax.swing.JButton button_DeleteTrack;
    private javax.swing.JButton button_change;
    private javax.swing.JCheckBox checkBox_Approved;
    private javax.swing.JLabel image_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private javax.swing.JTable table_tracks;
    private javax.swing.JTextField text_AlbumArtist;
    private javax.swing.JTextField text_AlbumTitle;
    private javax.swing.JTextField text_Genre;
    private javax.swing.JTextField text_comment;
    private javax.swing.JTextField text_id;
    // End of variables declaration//GEN-END:variables
}
